

apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend
  namespace: frontend
  labels:
    app: nextjs-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

